// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_yagyyfzr1JbFmP26A7tWU_afY7PpigQ',
    appId: '1:84780312511:web:2e62704cc60ba1ca91630a',
    messagingSenderId: '84780312511',
    projectId: 'blinq-e5be3',
    authDomain: 'blinq-e5be3.firebaseapp.com',
    storageBucket: 'blinq-e5be3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0sz9_cPIo-o0GuJqJpAQy1xVLW8QoYIA',
    appId: '1:84780312511:android:7ee3d8fb6e331b0e91630a',
    messagingSenderId: '84780312511',
    projectId: 'blinq-e5be3',
    storageBucket: 'blinq-e5be3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGXEnr4Ap-AKnE--mvnr7rGcEM7mVjsNs',
    appId: '1:84780312511:ios:c6fb573995deefd291630a',
    messagingSenderId: '84780312511',
    projectId: 'blinq-e5be3',
    storageBucket: 'blinq-e5be3.appspot.com',
    iosBundleId: 'pk.blinq.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGXEnr4Ap-AKnE--mvnr7rGcEM7mVjsNs',
    appId: '1:84780312511:ios:52323ca2d6fde32291630a',
    messagingSenderId: '84780312511',
    projectId: 'blinq-e5be3',
    storageBucket: 'blinq-e5be3.appspot.com',
    iosBundleId: 'pk.blinq.app.RunnerTests',
  );
}
